BOARD_TAG    = pro5v328
MONITOR_PORT = /dev/ttyUSB0
ARDUINO_LIBS = OneWire DallasTemperature
ARDUINO_DIR  = /data/tmp/arduino-1.6.8
BOARDS_TXT   = /data/tmp/arduino-1.6.8/hardware/arduino/avr/boards.txt
ALTERNATE_CORE_PATH = /data/tmp/arduino-1.6.8/hardware/arduino/avr/cores/arduino
include /usr/share/arduino/Arduino.mk
